package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MechanicalEquipment implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private String packageName;

    public MechanicalEquipment() {
       
    }

    public String getPackageName(){
        return this.packageName;
    }

    public void setPackageName(String packageName){
         this.packageName = packageName;
    } 
    

}