package com;

import java.util.HashMap;
import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MechanicalEquipment implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private String id;
    private Map<Object, Object> data;

    public MechanicalEquipment() {
       
    }

    public String getId(){
        return this.id;
    }

    public void setId(String id){
         this.id = id;
    } 

    public void setData(Map<Object, Object> map)
    {
        this.data = map;
    }
    public Map<Object, Object> getData()
    {
    return this.data;
    }
 
}